[package]
authors = ["Evgeniy Terekhin <e_terekhin@pm.me>"]
edition = "2021"
name = "faq_bot"
version = "0.1.0"

[features]
tools = []

[dependencies.redis]
version = "0.21"
default-features = false
features = ["aio", "cluster", "connection-manager", "tokio-comp"]

[[bin]]
name = "validate_data"
path = "bin/validate_data/main.rs"
required-features = ["tools"]
