[package]
authors = ["Evgeniy Terekhin <e_terekhin@pm.me>"]
edition = "2021"
name = "faq_bot"
version = "0.1.0"

[features]
tools = ["regex", "once_cell"]

[dependencies]
anyhow = "1"
clap = { version = "3.0.0-rc.4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

regex = { version = "1", optional = true }
once_cell = { version = "1", optional = true }

[dependencies.redis]
version = "0.21"
default-features = false
features = ["aio", "cluster", "connection-manager", "tokio-comp"]

[[bin]]
name = "validate_data"
path = "bin/validate_data/main.rs"
required-features = ["tools"]
