http:
  bind: 127.0.0.1:8888
  tls:
    cert: "./ssl/cert.pem"
    key: "./ssl/key.pem"
feedback:
  ack_ttl: 5s
  timeout: 30s
db:
  nodes:
    - redis://127.0.0.1:30001
    - redis://127.0.0.1:30002
    - redis://127.0.0.1:30003
    - redis://127.0.0.1:30004
    - redis://127.0.0.1:30005
    - redis://127.0.0.1:30006
  scripts_path: ./redis
  connection_timeout: 1m
logs:
  type: stdout
  # type: file
  # dir: ./logs
  # prefix: log
