http:
  bind: 127.0.0.1:8888
  tls:
    cert: "./ssl/cert.pem"
    key: "./ssl/key.pem"
feedback:
  ack_ttl: 5s
  timeout: 30s
db:
  nodes:
    - redis://127.0.0.1:7000
    - redis://127.0.0.1:7001
    - redis://127.0.0.1:7002
    - redis://127.0.0.1:7003
    - redis://127.0.0.1:7004
    - redis://127.0.0.1:7005
  scripts_path: ./redis
  connection_timeout: 1m
